name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libsdl2-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Create Archive
      run: |
        tar -cavf ecnavda-yobemag_linux.zip build/ecnavda-yobemag LICENSE
        tar -cavf ecnavda-yobemag_linux.tar.gz build/ecnavda-yobemag LICENSE

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        prerelease: true
        name: "Development Build"
        files: |
          ecnavda-yobemag_linux.zip
          ecnavda-yobemag_linux.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup dependencies
      run: |
        vcpkg install sdl2:x64-windows

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -T clangcl -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Archive
      run: tar -cavf ecnavda-yobemag_windows.zip ecnavda-yobemag.exe SDL2.dll LICENSE
